logging.level:
  org.hibernate.SQL: DEBUG
---
spring:
  application:
    name: turingservice
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://us-cdbr-iron-east-02.cleardb.net/heroku_ade11665172ab54?reconnect=true
    username: bfa091abc839a6
    password: 37b3adab
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      temp:
        use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    property-naming-strategy: SNAKE_CASE

security:
  jwt:
    token:
      secret-key: turingservicebreakmykey
      expire-length: 86400000
stripe:
  api-key: sk_test_lomdOfxbm7QDgZWvR82UhV6D
  secret: whsec_Qo92LgLsAVIBkZOson6d95wLC63jrDPE


#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#logging:
#  level:
#    org:
#      hibernate: ERROR
