logging.level:
  org.hibernate.SQL: DEBUG
---
spring:
  application:
    name: turingservice
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tshirtshop?useSSL=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      temp:
        use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    property-naming-strategy: SNAKE_CASE

security:
  jwt:
    token:
      secret-key: turingservicebreakmykey
      expire-length: 86400000
stripe:
  api-key: sk_test_lomdOfxbm7QDgZWvR82UhV6D


#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#logging:
#  level:
#    org:
#      hibernate: ERROR
